
import java.awt.Color;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Background.java
 *
 * Created on 25-Jan-2011, 10:54:06 AM
 */

/**
 *
 * @author Jazbel Wang
 */
public class Background extends javax.swing.JDialog {

    //VARIABLE DECLARATION
    NewCard nc;

    /** Creates new form Background
     * @param parent - the frame of this dialog
     * @param modal - true for a modal dialog, false for one that allows other windows to be active at the same time
     */
    public Background(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        redB = new javax.swing.JButton();
        blueB = new javax.swing.JButton();
        yellowB = new javax.swing.JButton();
        greenB = new javax.swing.JButton();
        violetB = new javax.swing.JButton();
        blackB = new javax.swing.JButton();
        grey = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Please choose a colour as the background of your card:");

        jToolBar1.setBackground(new java.awt.Color(204, 204, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        jToolBar1.setFloatable(false);
        jToolBar1.setForeground(new java.awt.Color(204, 204, 255));
        jToolBar1.setRollover(true);

        redB.setBackground(new java.awt.Color(255, 0, 0));
        redB.setForeground(new java.awt.Color(255, 0, 0));
        redB.setText("      ");
        redB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redBActionPerformed(evt);
            }
        });
        jToolBar1.add(redB);

        blueB.setBackground(new java.awt.Color(0, 0, 255));
        blueB.setForeground(new java.awt.Color(0, 0, 255));
        blueB.setText("      ");
        blueB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueBActionPerformed(evt);
            }
        });
        jToolBar1.add(blueB);

        yellowB.setBackground(new java.awt.Color(255, 255, 0));
        yellowB.setForeground(new java.awt.Color(255, 255, 0));
        yellowB.setText("      ");
        yellowB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowBActionPerformed(evt);
            }
        });
        jToolBar1.add(yellowB);

        greenB.setBackground(new java.awt.Color(0, 255, 0));
        greenB.setForeground(new java.awt.Color(0, 255, 0));
        greenB.setText("      ");
        greenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenBActionPerformed(evt);
            }
        });
        jToolBar1.add(greenB);

        violetB.setBackground(new java.awt.Color(204, 0, 204));
        violetB.setForeground(new java.awt.Color(204, 0, 204));
        violetB.setText("      ");
        violetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                violetBActionPerformed(evt);
            }
        });
        jToolBar1.add(violetB);

        blackB.setBackground(new java.awt.Color(0, 0, 0));
        blackB.setText("      ");
        blackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackBActionPerformed(evt);
            }
        });
        jToolBar1.add(blackB);

        grey.setBackground(new java.awt.Color(204, 204, 204));
        grey.setText("      ");
        grey.setFocusable(false);
        grey.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        grey.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        grey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greyActionPerformed(evt);
            }
        });
        jToolBar1.add(grey);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Method that sets the background color of the card to red
    private void redBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redBActionPerformed
        nc.drawingArea1.setBackground(Color.red);
}//GEN-LAST:event_redBActionPerformed
    //Method that sets the background color of the card to blue
    private void blueBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueBActionPerformed
        nc.drawingArea1.setBackground(Color.blue);
}//GEN-LAST:event_blueBActionPerformed
    //Method that sets the background color of the card to yellow
    private void yellowBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowBActionPerformed
        nc.drawingArea1.setBackground(Color.yellow);
}//GEN-LAST:event_yellowBActionPerformed
    //Method that sets the background color of the card to green
    private void greenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenBActionPerformed
        nc.drawingArea1.setBackground(Color.green);
}//GEN-LAST:event_greenBActionPerformed
    //Method that sets the background color of the card to violet
    private void violetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_violetBActionPerformed
        nc.drawingArea1.setBackground(Color.MAGENTA);
}//GEN-LAST:event_violetBActionPerformed
    //Method that sets the background color of the card to black
    private void blackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackBActionPerformed
        nc.drawingArea1.setBackground(Color.black);
}//GEN-LAST:event_blackBActionPerformed
    //Method that sets the background color of the card to grey
    private void greyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greyActionPerformed
        nc.drawingArea1.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_greyActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Background dialog = new Background(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blackB;
    private javax.swing.JButton blueB;
    private javax.swing.JButton greenB;
    private javax.swing.JButton grey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton redB;
    public javax.swing.JButton violetB;
    private javax.swing.JButton yellowB;
    // End of variables declaration//GEN-END:variables

}
