/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CardBuilderFrame.java
 *
 * Created on 12-Jan-2011, 11:13:29 AM
 */

/**
 *
 * @author 072695679
 */

import java.io.BufferedInputStream;
import java.io.FileInputStream;
import javazoom.jl.player.Player; //this is to play mp3 music

public class CardMakerInterface extends javax.swing.JFrame {

    Thread musicalThread;  //this is a separate thread that will play music and still let other things go on
    Player player;  //this is to hold the song being played

    /** Creates new form CardBuilderFrame */
    public CardMakerInterface() {
        initComponents();
        setUpPlayer("happybday.mp3");     //this just calls the method to load the mp3 file and
        musicalThread = new Thread() {  //this creates a thread to play the music and starts it.

            public void run() {
                try {
                    player.play();
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        };
        musicalThread.start();
    }

    //copy this method to your own program and it will load an mp3 file into a player
    public void setUpPlayer(String filename) {
        try {
            FileInputStream fis = new FileInputStream(filename);
            BufferedInputStream bis = new BufferedInputStream(fis);
            player = new Player(bis);
        } catch (Exception e) {
            System.out.println("Problem playing file " + filename);
            System.out.println(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newCard1 = new NewCard();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        newCardMItem = new javax.swing.JMenuItem();
        saveMItem = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        undoMItem = new javax.swing.JMenuItem();
        font = new javax.swing.JMenuItem();
        bgMItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        file.setText("File");

        newCardMItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newCardMItem.setText("New Card");
        newCardMItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCardMItemActionPerformed(evt);
            }
        });
        file.add(newCardMItem);

        saveMItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMItem.setText("Save");
        saveMItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMItemActionPerformed(evt);
            }
        });
        file.add(saveMItem);

        jMenuBar1.add(file);

        edit.setText("Edit");

        undoMItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        undoMItem.setText("Undo");
        undoMItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoMItemActionPerformed(evt);
            }
        });
        edit.add(undoMItem);

        font.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        font.setText("Font");
        font.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontActionPerformed(evt);
            }
        });
        edit.add(font);

        bgMItem.setText("Background");
        edit.add(bgMItem);

        jMenuBar1.add(edit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newCard1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fontActionPerformed

    private void undoMItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoMItemActionPerformed

    }//GEN-LAST:event_undoMItemActionPerformed

    private void newCardMItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCardMItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCardMItemActionPerformed

    private void saveMItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMItemActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardMakerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bgMItem;
    private javax.swing.JMenu edit;
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem font;
    private javax.swing.JMenuBar jMenuBar1;
    private NewCard newCard1;
    private javax.swing.JMenuItem newCardMItem;
    private javax.swing.JMenuItem saveMItem;
    private javax.swing.JMenuItem undoMItem;
    // End of variables declaration//GEN-END:variables

}
