
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DrawingArea.java
 *
 * Created on 12-Jan-2011, 11:17:20 AM
 */
/**
 *
 * @author 072695679
 */
public class DrawingAreaTest extends javax.swing.JPanel {

    public Image toDraw;
    int x1 = -1, y1 = -1, x2 = -1, y2 = -1;
    Color colour = Color.RED;
    boolean line = false, firework = false;
    String text = "";
    int button = 0;

    /** Creates new form DrawingArea */
    public DrawingAreaTest() {
        initComponents();
    }

    public void paintComponent(Graphics g) {
        //      System.out.println(toDraw);
        g.setColor(colour);
        //Following code is for display images
        if (button == 1)//&& x2 != 0 && y2 != 0)
        {
            g.drawImage(toDraw, x1, y1, Math.abs(x1 - x2), Math.abs(y1 - y2), this);
        }
        //Following code is for drawing a line
        if (button == 2 && x1 > 0 && y1 > 0 && x2 > 0 && y2 > 0) {
            g.drawLine(x1, y1, x2, y2);
            repaint();
        }
        //Following code is for displaying text
        if (button == 3) {
            g.drawString(text, x1, y1);
            repaint();
        }
        //Following code is for drawing a firework
        if (button == 4) {
            g.drawLine(x1, y1, x2, y2);
        }
        line = false;


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
