
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CardMakerGUI.java
 *
 * Created on 7-Jan-2011, 11:20:55 AM
 */
/**
 *
 * @author Jazbel Wang
 */
public class MainMenu extends javax.swing.JPanel {

    /** Creates new MainMenu */
    public MainMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dimension = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOfDim = new javax.swing.JList();
        type = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listOfTypes = new javax.swing.JList();
        createB = new javax.swing.JButton();
        instruction = new java.awt.Label();

        dimension.setText("Dimensions: ");

        listOfDim.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "4.25\" x 5.5\"", "5\" x 7.5\"", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listOfDim);

        type.setText("Type of Card: ");

        listOfTypes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Happy Birthday", "Thank You", "Congratulations", "Happy Valentine's", "Merry Christmas", "Get Well Soon" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listOfTypes);

        createB.setText("Create");
        createB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBActionPerformed(evt);
            }
        });

        instruction.setText("Main Menu: Create a new card");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(instruction, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(201, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createB)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dimension)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(type)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instruction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dimension)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(createB)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    //Method to create a new card/CardMakerFrame
    private void createBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBActionPerformed
        //Get the choice that the user makes
        String chosen = "";
        chosen = (String) listOfTypes.getSelectedValue();
        System.out.println(chosen + ":" + chosen.length());
        CardMakerFrame cbf = null;                           
        //Pass on the key word for file access to CardMakerFrame
        if (chosen.equals("")){
            JOptionPane.showMessageDialog(createB, "Sorry, you did not choose a type of card to generate. Please make sure you select on from the list.");
        }
        //Create a CardMakerFrame based on the choice the user makes to set the right images
        if (chosen.equals("Happy Birthday")) {
            cbf = new CardMakerFrame("Birthday Card");
        } else if (chosen.equals("Thank You")) {
            cbf = new CardMakerFrame("Thank You Card");
        } else if (chosen.equals("Congratulations")) {
            cbf = new CardMakerFrame("Congratulations");
        } else if (chosen.equals("Happy Valentine's")) {
            cbf = new CardMakerFrame("Happy Valentine's");
        } else if (chosen.equals("Merry Christmas")) {
            cbf = new CardMakerFrame("Merry Christmas");
        } else if (chosen.equals("Get Well Soon")) {
            cbf = new CardMakerFrame("Get Well Soon");
        }
        //Make the frame of this panel invisible
        getTopLevelAncestor().setVisible(false);
        cbf.mmf = (MainMenuFrame) getTopLevelAncestor();
        //Set the cardMakerFrame visible
        cbf.setVisible(true);


    }//GEN-LAST:event_createBActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createB;
    private javax.swing.JLabel dimension;
    private java.awt.Label instruction;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listOfDim;
    private javax.swing.JList listOfTypes;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
